TRAVERSAL_LIST = [
    'Deep',
    'Shallow',
    'SoftDeleted',
    'Associated'
]

FOLDER_LIST = [
        'msgfolderroot',
        'calendar',
        'contacts',
        'deleteditems',
        'drafts',
        'inbox',
        'journal',
        'notes',
        'outbox',
        'sentitems',
        'tasks',
        'junkemail',
        'searchfolders',
        'voicemail',
        'recoverableitemsdeletions',
        'recoverableitemsversions',
        'recoverableitemspurges',
        'recipientcache',
        'quickcontacts',
        'conversationhistory',
        'todosearch',
        'mycontacts',
        'imcontactlist',
        'peopleconnect',
        'favorites'
    ]

MESSAGE_ELEMENTS = {
   "MimeContent": None,
   "ItemClass": [
       'AcceptItem',
       'CalendarItem',
       'Contact',
       'Conversation',
       'DeclineItem',
       'DistributionList',
       'GlobalItemClass',
       'Item',
       'MeetingCancellation',
       'MeetingMessage',
       'MettingRequest',
       'MeetingResponse',
       'Message',
       'RemoveItem',
       'Task',
       'TentativelyAcceptItem'
   ],
   "Subject": None,
   "Sensitivity": [
       'Normal',
       'Personal',
       'Private',
       'Confidential'
   ],
   "Body": {
       'BodyType': [
           'HTML',
           'Text'
       ],
       'IsTruncated': [
           'true',
           'false'
       ]
   },
   "Attachments": {
       'FileAttachment':{
           'Name': None,
           'IsInline': ['true', 'false'],
           'Content': None
       }
   },
   "Importance": [
       'Low',
       'Normal',
       'High'
   ],
   "IsSubmitted": [
       'true',
       'false'
   ],
   "IsDraft": [
       'true',
       'false'
   ],
   "DisplayCc": None,
   "DisplayTo": None,
   "Sender": {
       'Mailbox': {
           'Name': None,
           'EmailAddress': None,
           'MailboxType': [
               'Mailbox',
               'PublicDL',
               'PrivateDl',
               'Contact',
               'PublicFolder',
               'Unknown',
               'OneOff',
               'GroupMailbox'
           ]
       }
   },
   "ToRecipients": {
       'Mailbox': {
           'Name': None,
           'EmailAddress': None,
           'MailboxType': [
               'Mailbox',
               'PublicDL',
               'PrivateDl',
               'Contact',
               'PublicFolder',
               'Unknown',
               'OneOff',
               'GroupMailbox'
           ]
       }
   },
   "CcRecipients": {
       'Mailbox': {
           'Name': None,
           'EmailAddress': None,
           'MailboxType': [
               'Mailbox',
               'PublicDL',
               'PrivateDl',
               'Contact',
               'PublicFolder',
               'Unknown',
               'OneOff',
               'GroupMailbox'
           ]
       }
   },
   "BccRecipients": {
       'Mailbox': {
           'Name': None,
           'EmailAddress': None,
           'MailboxType': [
               'Mailbox',
               'PublicDL',
               'PrivateDl',
               'Contact',
               'PublicFolder',
               'Unknown',
               'OneOff',
               'GroupMailbox'
           ]
       }
   },
   "IsReadReceiptRequested": [
       'true',
       'false'
   ],
   "IsDeliveryReceiptRequested": [
       'true',
       'false'
   ],
   "From": {
       'Mailbox': {
           'Name': None,
           'EmailAddress': None,
           'MailboxType': [
               'Mailbox',
               'PublicDL',
               'PrivateDl',
               'Contact',
               'PublicFolder',
               'Unknown',
               'OneOff',
               'GroupMailbox'
           ]
       }
   },
   "IsRead": [
       'true',
       'false'
   ],
   "IsResponseRequested": [
       'true'
   ]
}

SEARCH_FILTERS = {
    'Contains': {
        'ContainmentMode': [
            'FullString',
            'Prefixed',
            'Substring',
            'PrefixOnWords',
            'ExactPhrase'
        ],
        'ContainmentComparison': [
            'Exact',
            'IgnoreCase',
            'IgnoreNonSpacingCharacters',
            'Loose',
            'IgnoreCaseAndNonSpacingCharacters',
            'LooseAndIgnoreCase',
            'LooseAndIgnoreNonSpace',
            'LooseAndIgnoreCaseAndIgnoreNonSpace'
        ]
    },
    'Excludes': {
        'Bitmask': []
    },
    'Exists': {},
    'IsEqualTo': {
        'FieldURIOrConstant': []
    },
    'IsNotEqualTo': {},
    'IsGreaterThan': {},
    'IsGreaterThanOrEqualTo': {},
    'IsLessThan': {},
    'IsLessThanOrEqualTo': {}
}

FIELD_URI_MAP = {
    'folder': [
        "FolderId",
        "ParentFolderId",
        "DisplayName",
        "UnreadCount",
        "TotalCount",
        "ChildFolderCount",
        "FolderClass",
        "SearchParameters",
        "ManagedFolderInformation",
        "PermissionSet",
        "EffectiveRights",
        "SharingEffectiveRights"
    ],
    'item': [
        "ItemId",
        "ParentFolderId",
        "ItemClass",
        "MimeContent",
        "Attachments",
        "Subject",
        "DateTimeReceived",
        "Size",
        "Categories",
        "HasAttachments",
        "Importance",
        "InReplyTo",
        "InternetMessageHeaders",
        "IsAssociated",
        "IsDraft",
        "IsFromMe",
        "IsResend",
        "IsSubmitted",
        "IsUnmodified",
        "DateTimeSent",
        "DateTimeCreated",
        "Body",
        "ResponseObjects",
        "Sensitivity",
        "ReminderDueBy",
        "ReminderIsSet",
        "ReminderNextTime",
        "ReminderMinutesBeforeStart",
        "DisplayTo",
        "DisplayCc",
        "Culture",
        "EffectiveRights",
        "LastModifiedName",
        "LastModifiedTime",
        "ConversationId",
        "UniqueBody",
        "Flag",
        "StoreEntryId",
        "InstanceKey",
        "NormalizedBody",
        "EntityExtractionResult",
        "ArchiveTag",
        "RetentionDate",
        "Preview",
        "NextPredictedAction",
        "GroupingAction",
        "PredictedActionReasons",
        "IsClutter",
        "RightsManagementLicenseData",
        "BlockStatus",
        "HasBlockedImages",
        "WebClientReadFormQueryString",
        "WebClientEditFormQueryString",
        "TextBody",
        "IconIndex",
        "MimeContentUTF8"
    ],
    'message': [
        "ConversationIndex",
        "ConversationTopic",
        "InternetMessageId",
        "IsRead",
        "IsResponseRequested",
        "IsReadReceiptRequested",
        "IsDeliveryReceiptRequested",
        "ReceivedBy",
        "ReceivedRepresenting",
        "References",
        "ReplyTo",
        "From",
        "Sender",
        "ToRecipients",
        "CcRecipients",
        "BccRecipients",
        "ApprovalRequestData",
        "VotingInformation",
        "ReminderMessageData",
    ],
    'meeting': [
        "AssociatedCalendarItemId",
        "IsDelegated",
        "IsOutOfDate",
        "HasBeenProcessed",
        "ResponseType",
        "ProposedStart",
        "PropsedEnd",
    ],
    'meetingRequest': [
        "MeetingRequestType",
        "IntendedFreeBusyStatus",
        "ChangeHighlights",
    ],
    'calendar': [
        "Start",
        "End",
        "OriginalStart",
        "StartWallClock",
        "EndWallClock",
        "StartTimeZoneId",
        "EndTimeZoneId",
        "IsAllDayEvent",
        "LegacyFreeBusyStatus",
        "Location",
        "When",
        "IsMeeting",
        "IsCancelled",
        "IsRecurring",
        "MeetingRequestWasSent",
        "IsResponseRequested",
        "CalendarItemType",
        "MyResponseType",
        "Organizer",
        "RequiredAttendees",
        "OptionalAttendees",
        "Resources",
        "ConflictingMeetingCount",
        "AdjacentMeetingCount",
        "ConflictingMeetings",
        "AdjacentMeetings",
        "Duration",
        "TimeZone",
        "AppointmentReplyTime",
        "AppointmentSequenceNumber",
        "AppointmentState",
        "Recurrence",
        "FirstOccurrence",
        "LastOccurrence",
        "ModifiedOccurrences",
        "DeletedOccurrences",
        "MeetingTimeZone",
        "ConferenceType",
        "AllowNewTimeProposal",
        "IsOnlineMeeting",
        "MeetingWorkspaceUrl",
        "NetShowUrl",
        "UID",
        "RecurrenceId",
        "DateTimeStamp",
        "StartTimeZone",
        "EndTimeZone",
        "JoinOnlineMeetingUrl",
        "OnlineMeetingSettings",
        "IsOrganizer",
    ],
    'task': [
        "ActualWork",
        "AssignedTime",
        "BillingInformation",
        "ChangeCount",
        "Companies",
        "CompleteDate",
        "Contacts",
        "DelegationState",
        "Delegator",
        "DueDate",
        "IsAssignmentEditable",
        "IsComplete",
        "IsRecurring",
        "IsTeamTask",
        "Mileage",
        "Owner",
        "PercentComplete",
        "Recurrence",
        "StartDate",
        "Status",
        "StatusDescription",
        "TotalWork",
    ],
    'contacts': [
        "Alias",
        "AssistantName",
        "Birthday",
        "BusinessHomePage",
        "Children",
        "Companies",
        "CompanyName",
        "CompleteName",
        "ContactSource",
        "Culture",
        "Department",
        "DisplayName",
        "DirectoryId",
        "DirectReports",
        "EmailAddresses",
        "FileAs",
        "FileAsMapping",
        "Generation",
        "GivenName",
        "ImAddresses",
        "Initials",
        "JobTitle",
        "Manager",
        "ManagerMailbox",
        "MiddleName",
        "Mileage",
        "MSExchangeCertificate",
        "Nickname",
        "Notes",
        "OfficeLocation",
        "PhoneNumbers",
        "PhoneticFullName",
        "PhoneticFirstName",
        "PhoneticLastName",
        "Photo",
        "PhysicalAddresses",
        "PostalAddressIndex",
        "Profession",
        "SpouseName",
        "Surname",
        "WeddingAnniversary",
        "UserSMIMECertificate",
        "HasPicture",
    ],
    'conversation': [
        "ConversationId",
        "ConversationTopic",
        "UniqueRecipients",
        "GlobalUniqueRecipients",
        "UniqueUnreadSenders",
        "GlobalUniqueUnreadSenders",
        "UniqueSenders",
        "GlobalUniqueSenders",
        "LastDeliveryTime",
        "GlobalLastDeliveryTime",
        "Categories",
        "GlobalCategories",
        "FlagStatus",
        "GlobalFlagStatus",
        "HasAttachments",
        "GlobalHasAttachments",
        "HasIrm",
        "GlobalHasIrm",
        "MessageCount",
        "GlobalMessageCount",
        "UnreadCount",
        "GlobalUnreadCount",
        "Size",
        "GlobalSize",
        "ItemClasses",
        "GlobalItemClasses",
        "Importance",
        "GlobalImportance",
        "ItemIds",
        "GlobalItemIds",
        "LastModifiedTime",
        "InstanceKey",
        "Preview",
        "GlobalParentFolderId",
        "NextPredictedAction",
        "GroupingAction",
        "IconIndex",
        "GlobalIconIndex",
        "DraftItemIds",
        "HasClutter",
    ],
    'persona': [
        "PersonaId",
        "PersonaType",
        "GivenName",
        "CompanyName",
        "Surname",
        "DisplayName",
        "EmailAddress",
        "FileAs",
        "HomeCity",
        "CreationTime",
        "RelevanceScore",
        "WorkCity",
        "PersonaObjectStatus",
        "FileAsId",
        "DisplayNamePrefix",
        "YomiCompanyName",
        "YomiFirstName",
        "YomiLastName",
        "Title",
        "EmailAddresses",
        "PhoneNumber",
        "ImAddress",
        "ImAddresses",
        "ImAddresses2",
        "ImAddresses3",
        "FolderIds",
        "Attributions",
        "DisplayNames",
        "Initials",
        "FileAses",
        "FileAsIds",
        "DisplayNamePrefixes",
        "GivenNames",
        "MiddleNames",
        "Surnames",
        "Generations",
        "Nicknames",
        "YomiCompanyNames",
        "YomiFirstNames",
        "YomiLastNames",
        "BusinessPhoneNumbers",
        "BusinessPhoneNumbers2",
        "HomePhones",
        "HomePhones2",
        "MobilePhones",
        "MobilePhones2",
        "AssistantPhoneNumbers",
        "CallbackPhones",
        "CarPhones",
        "HomeFaxes",
        "OrganizationMainPhones",
        "OtherFaxes",
        "OtherTelephones",
        "OtherPhones2",
        "Pagers",
        "RadioPhones",
        "TelexNumbers",
        "WorkFaxes",
        "Emails1",
        "Emails2",
        "Emails3",
        "BusinessHomePages",
        "School",
        "PersonalHomePages",
        "OfficeLocations",
        "BusinessAddresses",
        "HomeAddresses",
        "OtherAddresses",
        "Titles",
        "Departments",
        "CompanyNames",
        "Managers",
        "AssistantNames",
        "Professions",
        "SpouseNames",
        "Hobbies",
        "WeddingAnniversaries",
        "Birthdays",
        "Children",
        "Locations",
        "ExtendedProperties",
        "PostalAddress",
        "Bodies",
    ]
}
